flexquery:
  outputs:
    TEST:
      type: duckdb
      path: '.\\testdatabase.db'

    DEV:
      type: mssql
      server: '<your_dev_server>'
      database: '<your_dev_database>'

    PROD:
      type: mssql
      server: '<your_prod_server>'
      database: '<your_prod_database>'