# Please update below parameters as per your requirement to be used in SQL queries
client_id:
 - 7328923
 - 7312769

send_id:
  - 352607

employer_key: 
  - 'BTUL01'
  - 'IPCL01'
  - 'DAIU01'
  - 'SYNT76'

file_date: 
  - '20230413'
  - '20230414'
  - '20231212'

status: 'Active'

date_from: '2020-01-01'
date_to: '2020-12-31'

scheme_numbers:
 - 'N30652'
 - 'N30651'

employer_code:
  - 'DAIU01'